// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgkhvcubyckpcosrvyhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNna2h2Y3VieWNrcGNvc3J2eWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxNjMyNTksImV4cCI6MjA1MDczOTI1OX0.ths5zZ04f7r5A5al55LcH6RVO_WfYby_DAq8edno5d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);